'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5456
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("beautycomputing.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add_folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addusuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addusuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property addusuarioclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("addusuarioclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property adicionarusuariops() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("adicionarusuariops", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agenda() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agenda", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property agendaclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("agendaclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property aluno() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("aluno", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property alunoClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alunoClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anterior() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anterior", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property anteriorClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("anteriorClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backup() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backup", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property backupclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("backupclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg101() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg101", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cadastro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cadastroclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cadastroclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cancelarClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cancelarClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carrega() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carrega", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property carregando() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("carregando", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Chave() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chave", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cientes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cientes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cientes1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cientes1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cientesClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cientesClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Cópia_de_bg11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cópia_de_bg11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cursos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cursos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property cursosclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cursosclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editarClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editarClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property editarORIGINAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("editarORIGINAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property estoque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estoque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property estoqueclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("estoqueclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excluir() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluir", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property excluirClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("excluirClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fotos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fotos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property frontend() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("frontend", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property funcionarios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("funcionarios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property funcionariosClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("funcionariosClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo14() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo14", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo141() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo141", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo15() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo15", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundo8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundo8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property FundoADM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FundoADM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundocadastros() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundocadastros", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundocadastros1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundocadastros1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fundocadastros2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fundocadastros2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Fundousuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Fundousuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property gtk_print_report() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gtk_print_report", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property lista() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lista", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property listaClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("listaClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property menuClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("menuClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property minimizar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("minimizar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mulher() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mulher", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mulher1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mulher1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_file() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_file", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property novo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property novo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property novo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property novoClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("novoClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property people() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("people", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property personal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("personal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property primeiro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("primeiro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property primeiroClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("primeiroClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property procurar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("procurar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property procurarclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("procurarclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property proximo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proximo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property proximoClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("proximoClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relatorios() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatorios", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relatoriosClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatoriosClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relatoriosdealunos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatoriosdealunos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property relatoriosdeclientes() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("relatoriosdeclientes", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sairClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sairClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sairClaro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sairClaro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salvar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property salvarClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("salvarClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property servicos() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("servicos", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property servicosClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("servicosClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property servicosClaro1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("servicosClaro1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property telainicial() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("telainicial", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property telainicioprograma() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("telainicioprograma", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultimo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultimo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ultimoClaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ultimoClaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property usuario() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("usuario", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property voltar() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voltar", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property voltarclaro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voltarclaro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property webcam() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("webcam", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
